### PR TITLE
WebShareDialog: handle expired sessions

### PR DESCRIPTION
**Pull request by xjuan**
Open control center if account AttentionNeeded is true

https://phabricator.endlessm.com/T20960

### CODE REVIEW

**Comment by xjuan** [comment]
You can unpak seahorse from a debian package and run it locally by compiling the schemas and setting GSETTINGS_SCHEMA_DIR env variable

Here is a tarball with the compiled schemas [seahorse.zip](https://github.com/endlessm/eos-knowledge-lib/files/1725271/seahorse.zip)

GSETTINGS_SCHEMA_DIR=$HOME/seahorse/usr/share/glib-2.0/schemas/ seahorse/usr/bin/seahorse

**Comment by ptomato** [comment]
I still have this happening:
> But what I do see when I run com.endlessm.encyclopedia.en and try to share on Facebook, is that a blank window opens up and nothing happens.

I double-checked on SDK3 and it doesn't happen there.

**Comment by xjuan** [comment]
I think thats probably because I never added error handling, so if the internet connection fails you will get stuck with an blank window

Added https://phabricator.endlessm.com/T21193

**Comment by ptomato** [comment]
Maybe someone else should review this while the load-failed issue is being worked on? FWIW, I don't get the blank window on master.

**Comment by nedrichards** [comment]
Good point! We really need a better way of expressing capabilities into flatpak permissions.

**Comment by nedrichards** [comment]
Does it ever talk more specifically to the ControlCenter? you might also need a .* permission underneath that.

**Comment by xjuan** [comment]
No, it only activates a GtkAction from org.gnome.ControlCenter

**Pull request merged**
