### PR TITLE
Fix failing tests for SDK-6 (BuildStream)

### PR DESCRIPTION
**Pull request by dnohales**
So, I'm making this PR to organize myself and let you know what tests are failing when the test suite is ran with BuildStream, I have disabled those and I'm gonna push changes progressively when fixing those.

This PR plus the disabling of coverage in [endless-sdk-flatpak](https://github.com/endlessm/endless-sdk-flatpak/blob/master/elements/sdk/eos-knowledge-lib.bst#L29) make the test suite pass. We could merge this as is if we run out of time...

https://phabricator.endlessm.com/T30490

### CODE REVIEW

**Comment by dnohales** [comment]
Jenkins test this please.

**Comment by dnohales** [comment]
lol, it worked

**Comment by dnohales** [comment]
Jenkins test this please.

**Comment by dylanmccall** [comment]
I'm happy with this now, in conjunction with https://github.com/endlessm/endless-sdk-flatpak/commit/f8b667e54c7046b07f51b4f3f31dad9429cc6947. Tests all pass! Happy to merge any time :)

**Comment by dnohales** [comment]
@dylanmccall Thanks a lot for working on this, I was kind of uncertain on how to move forward on these, merging now.

**Pull request merged**
