### PR TITLE
T19428

### PR DESCRIPTION
**Pull request by tchx84**
https://phabricator.endlessm.com/T19428

### CODE REVIEW

**Comment by tchx84** [comment]
This can be merged after https://github.com/endlessm/eos-knowledge-lib/pull/1518

**Comment by tchx84** [comment]
@erikos @smspillaz does the discovery feed stuff depend on subscriptions.json?

**Comment by erikos** [comment]
Hi Martin, we only add a view fields to the manifest-override.json (like discovery-feed interface information, language...). No dependency on subscriptions.json

**Comment by smspillaz** [comment]
@tchx84 Yup, can confirm, no dependency on `subscriptions.json`. Thanks for checking!

**Comment by xjuan** [comment]
CR Pass

**Pull request merged**
