### PR TITLE
Add a ContentObjectModel for WordOfTheDay

### PR DESCRIPTION
**Pull request by erikos**
https://phabricator.endlessm.com/T17276

### CODE REVIEW

**Comment by smspillaz** [comment]
Looks good to me generally. We probably want one for Quotes too. Is this currently being constructed anywhere?

**Comment by erikos** [comment]
Thanks Sam for taking a look, yes, I will do Quotes next, just wanted to see if this is where we are heading.

**Comment by ptomato** [comment]
I thought eos-discovery-feed wasn't intended to depend on this library - wouldn't you have to put this somewhere else?

**Comment by erikos** [comment]
Added a ContentObjectModel for QuoteOfTheDay. 

We only use the Evergreen specific EkncContentObjectModel in the eos-knowledge-service to retrieve the content from the model, and that data is then forwarded to eos-discovery-feed. No dependency will be introduced for the e-d-f onto the knowledge-lib.

**Comment by ptomato** [comment]
I see. Would it be possible to keep this in eos-knowledge-services among the other evergreen-related code? Putting it here exposes it as API in our developer platform, and I don't think I agree with that.

**Comment by smspillaz** [comment]
@ptomato I think I'd agree with the sentiment here. The implementation is what potentially becomes tricky. The main problem is that we need to expose new fields specific to the WoTD/QoTD cards ("definition", "pronunciation", "type" etc) at the shard level. Those new fields have to propagate up the stack somehow.

We could retain the approach that we were using before and stuff them into `discoveryFeedContent`. I remember at least just before this we were field-stuffing into somewhat irrelevant fields like `synopsis`. I can't quite remember why that was, maybe @erikos can add more detail.

**Comment by erikos** [comment]
Follow up for eos-knowledge-services: https://github.com/endlessm/eos-knowledge-services/pull/14

Follow up for eos-discovery-feed: https://github.com/endlessm/eos-discovery-feed/pull/23/commits/0f3087d5cae95f27d265d7d97ead8942e3052dc1

**Comment by erikos** [comment]
Closing as we decided to go with another approach.

**Pull request closed without merging**
