### PR TITLE
build: Use $TMPDIR for $XDG_DATA_HOME in tests

### PR DESCRIPTION
**Pull request by ptomato**
This should ensure that g_get_user_data_dir() always returns something
that exists, even in a clean Jenkins environment.

https://phabricator.endlessm.com/T18932

### CODE REVIEW

**Comment by ebassi** [comment]
Would be nice to delete the temporary directory to avoid leaving around artefacts; I'm also not entirely sure if this will break distcheck.

**Comment by ptomato** [comment]
Hmm, there's not really a hook for Automake to delete the directory after the tests have run. Any suggestions?

**Comment by ebassi** [comment]
The way we do this upstream in GLib is to use a fixture init function that creates the directory and calls `g_setenv()`; then the fixture teardown function deletes the directory. For instance, [like this commit](https://git.gnome.org/browse/glib/commit/?id=0f5b523fac8b2d9b9305419937e51b6c87e765be).

**Comment by ptomato** [comment]
Good idea, here's an implementation.

**Comment by ebassi** [comment]
Looks great.

**Pull request merged**
