### PR TITLE
Fix content updates (eos3.1 branch only)

### PR DESCRIPTION
**Pull request by ptomato**
https://phabricator.endlessm.com/T14643

### CODE REVIEW

**Comment by mattdangerw** [comment]
Approach looks fine to me. Can definitely apply the same set of changes to the new C version without much trouble.

A little curious where this regression actually came from. Cause this synchronous update apply is new right? How was this actually working before?

Also @magcius if you want, might be good to look over the downloader changes here.

I'll work on a master version of this change.

**Comment by magcius** [comment]
Both of these patches look fine to me. I think the answer is that we always "won the race" before.

**Comment by ptomato** [comment]
The commit that "broke" things (i.e. changed from a race condition to a situation where things were initialized in the wrong order, period) was 860285713257c1bf65b46f8f8bd014a051b59725, but as Jasper said, this was already present.

**Comment by mattdangerw** [comment]
Alright lets go for it

CR pass

**Pull request merged**
